### ISSUE TITLE
3070ti 8G显卡使用GPU-6G-7B-CN模板开启加速后报错

### ISSUE THREAD

**Issue by ranranBi** [josStorer/RWKV-Runner#10]
INFO:     Started server process [2280]
INFO:     Waiting for application startup.
torch found: D:\AIGC\chatrvkw模型\py310\Lib\site-packages\torch\lib
torch set
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:49159 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:49159 - "GET /status HTTP/1.1" 200 OK
INFO:     127.0.0.1:49159 - "OPTIONS /update-config HTTP/1.1" 200 OK
max_tokens=4100 temperature=1.2 top_p=0.5 presence_penalty=0.4 frequency_penalty=0.4
INFO:     127.0.0.1:49159 - "POST /update-config HTTP/1.1" 200 OK
INFO:     127.0.0.1:49159 - "OPTIONS /switch-model HTTP/1.1" 200 OK
D:\AIGC\chatrvkw模型\py310\Lib\site-packages\_distutils_hack\__init__.py:18: UserWarning: Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`. This may lead to undesirable behaviors or errors. To avoid these issues, avoid using distutils directly, ensure that setuptools is installed in the traditional way (e.g. not an editable install), and/or make sure that setuptools is always imported before distutils.
  warnings.warn(
D:\AIGC\chatrvkw模型\py310\Lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Using D:\AIGC\chatrvkw模型\backend-python as PyTorch extensions root...
Ninja is required to load C++ extensions
INFO:     127.0.0.1:49159 - "POST /switch-model HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\AIGC\chatrvkw模型\backend-python\routes\config.py", line 36, in switch_model
    RWKV(
  File "pydantic\main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic\main.py", line 1102, in pydantic.main.validate_model
  File "D:\AIGC\chatrvkw模型\py310\Lib\site-packages\langchain\llms\rwkv.py", line 111, in validate_environment
    from rwkv.model import RWKV as RWKVMODEL
  File "D:\AIGC\chatrvkw模型\py310\Lib\site-packages\rwkv\model.py", line 78, in <module>
    load(
  File "D:\AIGC\chatrvkw模型\py310\Lib\site-packages\torch\utils\cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "D:\AIGC\chatrvkw模型\py310\Lib\site-packages\torch\utils\cpp_extension.py", line 1508, in _jit_compile
    _write_ninja_file_and_build_library(
  File "D:\AIGC\chatrvkw模型\py310\Lib\site-packages\torch\utils\cpp_extension.py", line 1592, in _write_ninja_file_and_build_library
    verify_ninja_availability()
  File "D:\AIGC\chatrvkw模型\py310\Lib\site-packages\torch\utils\cpp_extension.py", line 1648, in verify_ninja_availability
    raise RuntimeError("Ninja is required to load C++ extensions")
RuntimeError: Ninja is required to load C++ extensions

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\AIGC\chatrvkw模型\py310\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\AIGC\chatrvkw模型\py310\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "D:\AIGC\chatrvkw模型\py310\Lib\site-packages\fastapi\applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "D:\AIGC\chatrvkw模型\py310\Lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\AIGC\chatrvkw模型\py310\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\AIGC\chatrvkw模型\py310\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\AIGC\chatrvkw模型\py310\Lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "D:\AIGC\chatrvkw模型\py310\Lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "D:\AIGC\chatrvkw模型\py310\Lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\AIGC\chatrvkw模型\py310\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\AIGC\chatrvkw模型\py310\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "D:\AIGC\chatrvkw模型\py310\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "D:\AIGC\chatrvkw模型\py310\Lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "D:\AIGC\chatrvkw模型\py310\Lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\AIGC\chatrvkw模型\py310\Lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "D:\AIGC\chatrvkw模型\py310\Lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "D:\AIGC\chatrvkw模型\py310\Lib\site-packages\fastapi\routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "D:\AIGC\chatrvkw模型\py310\Lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "D:\AIGC\chatrvkw模型\py310\Lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\AIGC\chatrvkw模型\py310\Lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\AIGC\chatrvkw模型\py310\Lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\AIGC\chatrvkw模型\backend-python\routes\config.py", line 45, in switch_model
    raise HTTPException(status.HTTP_500_INTERNAL_SERVER_ERROR, "failed to load")
AttributeError: 'function' object has no attribute 'HTTP_500_INTERNAL_SERVER_ERROR'

**Comment by josStorer** [comment]
另外检查一下 py310\Lib\site-packages 目录下 torch的版本号是1.13，应该有这个文件夹torch-1.13.1+cu117.dist-info

**Comment by ranranBi** [comment]
是的，有torch-1.13.1+cu117.dist-info这个文件夹呢，关闭输入出，选择int8，只打开加速还是同样的报错，奇怪的是我另外一台电脑是正常的，标题写错了，显卡是4060的，3070ti的正常

**Comment by josStorer** [comment]
关闭加速能跑吗，可能是40系算子的问题

**Comment by ranranBi** [comment]
关闭加速是可以正常跑的，不过我自己搭建的用4060是可以正常加速的，不开启加速的回复速度太慢了

**Comment by josStorer** [comment]
1.0.7已推送40系算子

**Comment by ranranBi** [comment]
更新1.0.7，只开始加速，选择int8还是同样的报错

**Comment by ranranBi** [comment]
INFO:     Started server process [27576]
INFO:     Waiting for application startup.
torch found: D:\AIGC\chatrvkw-runnkw\py310\Lib\site-packages\torch\lib
torch set
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:63043 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:63043 - "GET /status HTTP/1.1" 200 OK
max_tokens=4100 temperature=1.2 top_p=0.5 presence_penalty=0.4 frequency_penalty=0.4
INFO:     127.0.0.1:63043 - "POST /update-config HTTP/1.1" 200 OK
D:\AIGC\chatrvkw-runnkw\py310\Lib\site-packages\_distutils_hack\__init__.py:18: UserWarning: Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`. This may lead to undesirable behaviors or errors. To avoid these issues, avoid using distutils directly, ensure that setuptools is installed in the traditional way (e.g. not an editable install), and/or make sure that setuptools is always imported before distutils.
  warnings.warn(
D:\AIGC\chatrvkw-runnkw\py310\Lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Using D:\AIGC\chatrvkw-runnkw\backend-python as PyTorch extensions root...
Ninja is required to load C++ extensions
INFO:     127.0.0.1:63043 - "POST /switch-model HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\AIGC\chatrvkw-runnkw\backend-python\routes\config.py", line 36, in switch_model
    RWKV(
  File "pydantic\main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic\main.py", line 1102, in pydantic.main.validate_model
  File "D:\AIGC\chatrvkw-runnkw\py310\Lib\site-packages\langchain\llms\rwkv.py", line 111, in validate_environment
    from rwkv.model import RWKV as RWKVMODEL
  File "D:\AIGC\chatrvkw-runnkw\py310\Lib\site-packages\rwkv\model.py", line 78, in <module>
    load(
  File "D:\AIGC\chatrvkw-runnkw\py310\Lib\site-packages\torch\utils\cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "D:\AIGC\chatrvkw-runnkw\py310\Lib\site-packages\torch\utils\cpp_extension.py", line 1508, in _jit_compile
    _write_ninja_file_and_build_library(
  File "D:\AIGC\chatrvkw-runnkw\py310\Lib\site-packages\torch\utils\cpp_extension.py", line 1592, in _write_ninja_file_and_build_library
    verify_ninja_availability()
  File "D:\AIGC\chatrvkw-runnkw\py310\Lib\site-packages\torch\utils\cpp_extension.py", line 1648, in verify_ninja_availability
    raise RuntimeError("Ninja is required to load C++ extensions")
RuntimeError: Ninja is required to load C++ extensions

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\AIGC\chatrvkw-runnkw\py310\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\AIGC\chatrvkw-runnkw\py310\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "D:\AIGC\chatrvkw-runnkw\py310\Lib\site-packages\fastapi\applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "D:\AIGC\chatrvkw-runnkw\py310\Lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\AIGC\chatrvkw-runnkw\py310\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\AIGC\chatrvkw-runnkw\py310\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\AIGC\chatrvkw-runnkw\py310\Lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "D:\AIGC\chatrvkw-runnkw\py310\Lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "D:\AIGC\chatrvkw-runnkw\py310\Lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\AIGC\chatrvkw-runnkw\py310\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\AIGC\chatrvkw-runnkw\py310\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "D:\AIGC\chatrvkw-runnkw\py310\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "D:\AIGC\chatrvkw-runnkw\py310\Lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "D:\AIGC\chatrvkw-runnkw\py310\Lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\AIGC\chatrvkw-runnkw\py310\Lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "D:\AIGC\chatrvkw-runnkw\py310\Lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "D:\AIGC\chatrvkw-runnkw\py310\Lib\site-packages\fastapi\routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "D:\AIGC\chatrvkw-runnkw\py310\Lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "D:\AIGC\chatrvkw-runnkw\py310\Lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\AIGC\chatrvkw-runnkw\py310\Lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\AIGC\chatrvkw-runnkw\py310\Lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\AIGC\chatrvkw-runnkw\backend-python\routes\config.py", line 45, in switch_model
    raise HTTPException(status.HTTP_500_INTERNAL_SERVER_ERROR, "failed to load")
AttributeError: 'function' object has no attribute 'HTTP_500_INTERNAL_SERVER_ERROR'

**Comment by josStorer** [comment]
进一下q群，283430436，我远程给你看
