### ISSUE TITLE
[CRITICAL] Python Error

### ISSUE THREAD

**Issue by lmsdscav** [josStorer/RWKV-Runner#105]
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    from routes import completion, config, state_cache
  File "/yanjiu/rwkv/backend-python/routes/completion.py", line 327, in <module>
    class EmbeddingsBody(BaseModel):
  File "/yanjiu/rwkv/backend-python/routes/completion.py", line 328, in EmbeddingsBody
    input: str | List[str] | List[List[int]]
TypeError: unsupported operand type(s) for |: 'type' and '_GenericAlias'

运行方式: python3 main.py

if change to python2
cannot found rwkv

**Comment by lmsdscav** [comment]
同时尝试过前端UI，使用CPU模型，点击启动后没有任何信息，启动失败

**Comment by josStorer** [comment]
https://github.com/josStorer/RWKV-Runner/commit/417389c5f6c48a36831b79c0d90836dc0acc384d

**Comment by josStorer** [comment]
已修复
