### ISSUE TITLE
[BUG]1.3.2版本训练报错：请先转换数据

### ISSUE THREAD

**Issue by Mingzefei** [josStorer/RWKV-Runner#108]
使用自带的 sample.jsonl 数据和默认的词表路径，点击转换后显示“数据转换成功”，之后点击“训练”，报错“请先转换数据”。

**Comment by josStorer** [comment]
没有检测新增依赖，在改了

**Comment by Mingzefei** [comment]
1.3.3 版本依然存在该问题。
已再次安装 python 依赖。

**Comment by Mingzefei** [comment]
软件有 debug 模式吗，保存运行中的报错？

**Comment by josStorer** [comment]
1.3.4 
https://github.com/josStorer/RWKV-Runner/releases/tag/v1.3.4

**Comment by Mingzefei** [comment]
1.3.4 WSL 栏显示报错，除基底模型外参数均默认。
基底模型：RWKV-4-Pile-1B5-Chn-testNovel-done-ctx2048-20230312.pth
```
apt cnMirror already set
pip installed
ninja installed
cuda installed
requirements satisfied
loading models/RWKV-4-Pile-1B5-Chn-testNovel-done-ctx2048-20230312.pth
Traceback (most recent call last):
File "./finetune/get_layer_and_embd.py", line 26, in <module>
model_file = open(sys.argv[1], "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'models/RWKV-4-Pile-1B5-Chn-testNovel-done-ctx2048-20230312.pth'
########## work in progress ##########
[2023-07-03 22:55:23,622] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
############################################################################
#
# RWKV-4 BF16 on 1x1 GPU, bsz 1x1x1=1, deepspeed_stage_2
#
# Data = ./finetune/json2binidx_tool/data/sample_text_document (binidx), ProjDir = lora-models
#
# Epoch = 0 to 19 (will continue afterwards), save every 5 epoch
#
# Each "epoch" = 1000 steps, 1000 samples, 150000 tokens
#
# Model = 6 n_layer, 512 n_embd, 150 ctx_len
# LoRA = enabled, 8 r, 32.0 alpha, 0.01 dropout, on att,ffn,time,ln
#
# Adam = lr 5e-05 to 5e-05, warmup 0 steps, beta (0.9, 0.999), eps 1e-08
#
# Found torch 1.13.1+cu117, recommend 1.13.1+cu117 or newer
# Found deepspeed 0.9.5, recommend 0.7.0 (faster than newer versions)
# Found pytorch_lightning 1.9.5, recommend 1.9.1 or newer
#
############################################################################
{'load_model': 'models/RWKV-4-Pile-1B5-Chn-testNovel-done-ctx2048-20230312.pth', 'wandb': '', 'proj_dir': 'lora-models', 'random_seed': -1, 'data_file': './finetune/json2binidx_tool/data/sample_text_document', 'data_type': 'binidx', 'vocab_size': 50277, 'ctx_len': 150, 'epoch_steps': 1000, 'epoch_count': 20, 'epoch_begin': 0, 'epoch_save': 5, 'micro_bsz': 1, 'n_layer': 6, 'n_embd': 512, 'dim_att': 512, 'dim_ffn': 2048, 'pre_ffn': 0, 'head_qk': 0, 'tiny_att_dim': 0, 'tiny_att_layer': -999, 'lr_init': 5e-05, 'lr_final': 5e-05, 'warmup_steps': 0, 'beta1': 0.9, 'beta2': 0.999, 'adam_eps': 1e-08, 'grad_cp': 0, 'my_pile_stage': 0, 'my_pile_shift': -1, 'my_pile_edecay': 0, 'layerwise_lr': 1, 'ds_bucket_mb': 200, 'my_img_version': 0, 'my_img_size': 0, 'my_img_bit': 0, 'my_img_clip': 'x', 'my_img_clip_scale': 1, 'my_img_l1_scale': 0, 'my_img_encoder': 'x', 'my_sample_len': 0, 'my_ffn_shift': 1, 'my_att_shift': 1, 'my_pos_emb': 0, 'load_partial': 0, 'magic_prime': 0, 'my_qa_mask': 0, 'my_testing': '', 'lora': True, 'lora_load': '', 'lora_r': 8, 'lora_alpha': 32.0, 'lora_dropout': 0.01, 'lora_parts': 'att,ffn,time,ln', 'logger': False, 'enable_checkpointing': False, 'default_root_dir': None, 'gradient_clip_val': 1.0, 'gradient_clip_algorithm': None, 'num_nodes': 1, 'num_processes': None, 'devices': '1', 'gpus': None, 'auto_select_gpus': None, 'tpu_cores': None, 'ipus': None, 'enable_progress_bar': True, 'overfit_batches': 0.0, 'track_grad_norm': -1, 'check_val_every_n_epoch': 100000000000000000000, 'fast_dev_run': False, 'accumulate_grad_batches': 8, 'max_epochs': -1, 'min_epochs': None, 'max_steps': -1, 'min_steps': None, 'max_time': None, 'limit_train_batches': None, 'limit_val_batches': None, 'limit_test_batches': None, 'limit_predict_batches': None, 'val_check_interval': None, 'log_every_n_steps': 100000000000000000000, 'accelerator': 'gpu', 'strategy': 'deepspeed_stage_2', 'sync_batchnorm': False, 'precision': 'bf16', 'enable_model_summary': True, 'num_sanity_val_steps': 0, 'resume_from_checkpoint': None, 'profiler': None, 'benchmark': None, 'reload_dataloaders_every_n_epochs': 0, 'auto_lr_find': False, 'replace_sampler_ddp': False, 'detect_anomaly': False, 'auto_scale_batch_size': False, 'plugins': None, 'amp_backend': None, 'amp_level': None, 'move_metrics_to_cpu': False, 'multiple_trainloader_mode': 'max_size_cycle', 'inference_mode': True, 'my_timestamp': '2023-07-03-22-55-24', 'betas': (0.9, 0.999), 'real_bsz': 1, 'run_name': '50277 ctx150 L6 D512'}
Using /root/.cache/torch_extensions/py38_cu117 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /root/.cache/torch_extensions/py38_cu117/wkv_150_bf16/build.ninja...
Building extension module wkv_150_bf16...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
RWKV_MY_TESTING
[1/3] /usr/bin/nvcc -DTORCH_EXTENSION_NAME=wkv_150_bf16 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /usr/local/lib/python3.8/dist-packages/torch/include -isystem /usr/local/lib/python3.8/dist-packages/torch/include/torch/csrc/api/include -isystem /usr/local/lib/python3.8/dist-packages/torch/include/TH -isystem /usr/local/lib/python3.8/dist-packages/torch/include/THC -isystem /usr/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -t 4 -std=c++17 -res-usage --maxrregcount 60 --use_fast_math -O3 -Xptxas -O3 --extra-device-vectorization -DTmax=150 -c /mnt/c/Users/Hua/win_workbench/text-gen-simple/finetune/lora/cuda/wkv_cuda_bf16.cu -o wkv_cuda_bf16.cuda.o
FAILED: wkv_cuda_bf16.cuda.o
/usr/bin/nvcc -DTORCH_EXTENSION_NAME=wkv_150_bf16 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /usr/local/lib/python3.8/dist-packages/torch/include -isystem /usr/local/lib/python3.8/dist-packages/torch/include/torch/csrc/api/include -isystem /usr/local/lib/python3.8/dist-packages/torch/include/TH -isystem /usr/local/lib/python3.8/dist-packages/torch/include/THC -isystem /usr/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -t 4 -std=c++17 -res-usage --maxrregcount 60 --use_fast_math -O3 -Xptxas -O3 --extra-device-vectorization -DTmax=150 -c /mnt/c/Users/Hua/win_workbench/text-gen-simple/finetune/lora/cuda/wkv_cuda_bf16.cu -o wkv_cuda_bf16.cuda.o
nvcc fatal : Unknown option 't'
[2/3] c++ -MMD -MF wkv_op_bf16.o.d -DTORCH_EXTENSION_NAME=wkv_150_bf16 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /usr/local/lib/python3.8/dist-packages/torch/include -isystem /usr/local/lib/python3.8/dist-packages/torch/include/torch/csrc/api/include -isystem /usr/local/lib/python3.8/dist-packages/torch/include/TH -isystem /usr/local/lib/python3.8/dist-packages/torch/include/THC -isystem /usr/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -c /mnt/c/Users/Hua/win_workbench/text-gen-simple/finetune/lora/cuda/wkv_op_bf16.cpp -o wkv_op_bf16.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 1900, in _run_ninja_build
subprocess.run(
File "/usr/lib/python3.8/subprocess.py", line 516, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "./finetune/lora/train.py", line 281, in <module>
from src.trainer import train_callback, generate_init_weight
File "/mnt/c/Users/Hua/win_workbench/text-gen-simple/finetune/lora/src/trainer.py", line 6, in <module>
from .model import LORA_CONFIG
File "/mnt/c/Users/Hua/win_workbench/text-gen-simple/finetune/lora/src/model.py", line 56, in <module>
wkv_cuda = load(name=f"wkv_{T_MAX}_bf16", sources=["finetune/lora/cuda/wkv_op_bf16.cpp", "finetune/lora/cuda/wkv_cuda_bf16.cu"], verbose=True, extra_cuda_cflags=["-t 4", "-std=c++17", "-res-usage", "--maxrregcount 60", "--use_fast_math", "-O3", "-Xptxas -O3", "--extra-device-vectorization", f"-DTmax={T_MAX}"])
File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 1284, in load
return _jit_compile(
File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 1508, in _jit_compile
_write_ninja_file_and_build_library(
File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 1623, in _write_ninja_file_and_build_library
_run_ninja_build(
File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 1916, in _run_ninja_build
raise RuntimeError(message) from e
RuntimeError: Error building extension 'wkv_150_bf16'
```

**Comment by josStorer** [comment]
尝试安装ubuntu22.04, 可能是版本过旧

**Comment by Mingzefei** [comment]
1.3.4 WSL 栏报错，参数除基底模型外默认。
基底模型：RWKV-4-Pile-1B5-Chn-testNovel-done-ctx2048-20230312.pth
```
apt cnMirror already set
pip installed
ninja installed
cuda installed
requirements satisfied
loading models/RWKV-4-Pile-1B5-Chn-testNovel-done-ctx2048-20230312.pth
--n_layer 24 --n_embd 2048
########## work in progress ##########
[2023-07-03 23:01:46,929] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
############################################################################
#
# RWKV-4 BF16 on 1x1 GPU, bsz 1x1x1=1, deepspeed_stage_2
#
# Data = ./finetune/json2binidx_tool/data/sample_text_document (binidx), ProjDir = lora-models
#
# Epoch = 0 to 19 (will continue afterwards), save every 5 epoch
#
# Each "epoch" = 1000 steps, 1000 samples, 150000 tokens
#
# Model = 24 n_layer, 2048 n_embd, 150 ctx_len
# LoRA = enabled, 8 r, 32.0 alpha, 0.01 dropout, on att,ffn,time,ln
#
# Adam = lr 5e-05 to 5e-05, warmup 0 steps, beta (0.9, 0.999), eps 1e-08
#
# Found torch 1.13.1+cu117, recommend 1.13.1+cu117 or newer
# Found deepspeed 0.9.5, recommend 0.7.0 (faster than newer versions)
# Found pytorch_lightning 1.9.5, recommend 1.9.1 or newer
#
############################################################################
{'load_model': 'models/RWKV-4-Pile-1B5-Chn-testNovel-done-ctx2048-20230312.pth', 'wandb': '', 'proj_dir': 'lora-models', 'random_seed': -1, 'data_file': './finetune/json2binidx_tool/data/sample_text_document', 'data_type': 'binidx', 'vocab_size': 50277, 'ctx_len': 150, 'epoch_steps': 1000, 'epoch_count': 20, 'epoch_begin': 0, 'epoch_save': 5, 'micro_bsz': 1, 'n_layer': 24, 'n_embd': 2048, 'dim_att': 2048, 'dim_ffn': 8192, 'pre_ffn': 0, 'head_qk': 0, 'tiny_att_dim': 0, 'tiny_att_layer': -999, 'lr_init': 5e-05, 'lr_final': 5e-05, 'warmup_steps': 0, 'beta1': 0.9, 'beta2': 0.999, 'adam_eps': 1e-08, 'grad_cp': 0, 'my_pile_stage': 0, 'my_pile_shift': -1, 'my_pile_edecay': 0, 'layerwise_lr': 1, 'ds_bucket_mb': 200, 'my_img_version': 0, 'my_img_size': 0, 'my_img_bit': 0, 'my_img_clip': 'x', 'my_img_clip_scale': 1, 'my_img_l1_scale': 0, 'my_img_encoder': 'x', 'my_sample_len': 0, 'my_ffn_shift': 1, 'my_att_shift': 1, 'my_pos_emb': 0, 'load_partial': 0, 'magic_prime': 0, 'my_qa_mask': 0, 'my_testing': '', 'lora': True, 'lora_load': '', 'lora_r': 8, 'lora_alpha': 32.0, 'lora_dropout': 0.01, 'lora_parts': 'att,ffn,time,ln', 'logger': False, 'enable_checkpointing': False, 'default_root_dir': None, 'gradient_clip_val': 1.0, 'gradient_clip_algorithm': None, 'num_nodes': 1, 'num_processes': None, 'devices': '1', 'gpus': None, 'auto_select_gpus': None, 'tpu_cores': None, 'ipus': None, 'enable_progress_bar': True, 'overfit_batches': 0.0, 'track_grad_norm': -1, 'check_val_every_n_epoch': 100000000000000000000, 'fast_dev_run': False, 'accumulate_grad_batches': 8, 'max_epochs': -1, 'min_epochs': None, 'max_steps': -1, 'min_steps': None, 'max_time': None, 'limit_train_batches': None, 'limit_val_batches': None, 'limit_test_batches': None, 'limit_predict_batches': None, 'val_check_interval': None, 'log_every_n_steps': 100000000000000000000, 'accelerator': 'gpu', 'strategy': 'deepspeed_stage_2', 'sync_batchnorm': False, 'precision': 'bf16', 'enable_model_summary': True, 'num_sanity_val_steps': 0, 'resume_from_checkpoint': None, 'profiler': None, 'benchmark': None, 'reload_dataloaders_every_n_epochs': 0, 'auto_lr_find': False, 'replace_sampler_ddp': False, 'detect_anomaly': False, 'auto_scale_batch_size': False, 'plugins': None, 'amp_backend': None, 'amp_level': None, 'move_metrics_to_cpu': False, 'multiple_trainloader_mode': 'max_size_cycle', 'inference_mode': True, 'my_timestamp': '2023-07-03-23-01-47', 'betas': (0.9, 0.999), 'real_bsz': 1, 'run_name': '50277 ctx150 L24 D2048'}
Using /root/.cache/torch_extensions/py38_cu117 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /root/.cache/torch_extensions/py38_cu117/wkv_150_bf16/build.ninja...
Building extension module wkv_150_bf16...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
RWKV_MY_TESTING
[1/3] /usr/bin/nvcc -DTORCH_EXTENSION_NAME=wkv_150_bf16 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /usr/local/lib/python3.8/dist-packages/torch/include -isystem /usr/local/lib/python3.8/dist-packages/torch/include/torch/csrc/api/include -isystem /usr/local/lib/python3.8/dist-packages/torch/include/TH -isystem /usr/local/lib/python3.8/dist-packages/torch/include/THC -isystem /usr/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -t 4 -std=c++17 -res-usage --maxrregcount 60 --use_fast_math -O3 -Xptxas -O3 --extra-device-vectorization -DTmax=150 -c /mnt/c/Users/Hua/win_workbench/text-gen-simple/finetune/lora/cuda/wkv_cuda_bf16.cu -o wkv_cuda_bf16.cuda.o
FAILED: wkv_cuda_bf16.cuda.o
/usr/bin/nvcc -DTORCH_EXTENSION_NAME=wkv_150_bf16 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /usr/local/lib/python3.8/dist-packages/torch/include -isystem /usr/local/lib/python3.8/dist-packages/torch/include/torch/csrc/api/include -isystem /usr/local/lib/python3.8/dist-packages/torch/include/TH -isystem /usr/local/lib/python3.8/dist-packages/torch/include/THC -isystem /usr/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -t 4 -std=c++17 -res-usage --maxrregcount 60 --use_fast_math -O3 -Xptxas -O3 --extra-device-vectorization -DTmax=150 -c /mnt/c/Users/Hua/win_workbench/text-gen-simple/finetune/lora/cuda/wkv_cuda_bf16.cu -o wkv_cuda_bf16.cuda.o
nvcc fatal : Unknown option 't'
[2/3] c++ -MMD -MF wkv_op_bf16.o.d -DTORCH_EXTENSION_NAME=wkv_150_bf16 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /usr/local/lib/python3.8/dist-packages/torch/include -isystem /usr/local/lib/python3.8/dist-packages/torch/include/torch/csrc/api/include -isystem /usr/local/lib/python3.8/dist-packages/torch/include/TH -isystem /usr/local/lib/python3.8/dist-packages/torch/include/THC -isystem /usr/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -c /mnt/c/Users/Hua/win_workbench/text-gen-simple/finetune/lora/cuda/wkv_op_bf16.cpp -o wkv_op_bf16.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 1900, in _run_ninja_build
subprocess.run(
File "/usr/lib/python3.8/subprocess.py", line 516, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "./finetune/lora/train.py", line 281, in <module>
from src.trainer import train_callback, generate_init_weight
File "/mnt/c/Users/Hua/win_workbench/text-gen-simple/finetune/lora/src/trainer.py", line 6, in <module>
from .model import LORA_CONFIG
File "/mnt/c/Users/Hua/win_workbench/text-gen-simple/finetune/lora/src/model.py", line 56, in <module>
wkv_cuda = load(name=f"wkv_{T_MAX}_bf16", sources=["finetune/lora/cuda/wkv_op_bf16.cpp", "finetune/lora/cuda/wkv_cuda_bf16.cu"], verbose=True, extra_cuda_cflags=["-t 4", "-std=c++17", "-res-usage", "--maxrregcount 60", "--use_fast_math", "-O3", "-Xptxas -O3", "--extra-device-vectorization", f"-DTmax={T_MAX}"])
File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 1284, in load
return _jit_compile(
File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 1508, in _jit_compile
_write_ninja_file_and_build_library(
File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 1623, in _write_ninja_file_and_build_library
_run_ninja_build(
File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 1916, in _run_ninja_build
raise RuntimeError(message) from e
RuntimeError: Error building extension 'wkv_150_bf16'
```

**Comment by Mingzefei** [comment]
> 尝试安装ubuntu22.04, 可能是版本过旧
我当前使用的 WSL2 是 20.04 版本，因为经常使用，不想升级到 22.04.
有没有其他方法，比如 docker？
另外训练时似乎在 WSL2 中直接安装依赖，可能会冲突或污染环境，有没有更好的方法？

**Comment by Mingzefei** [comment]
> 尝试安装ubuntu22.04, 可能是版本过旧

@josStorer 
我当前使用的 WSL2 是 20.04 版本，因为经常使用，不想升级到 22.04.
有没有其他方法，比如 docker？
另外训练时似乎在 WSL2 中直接安装依赖，可能会冲突或污染环境，有没有更好的方法？

**Comment by josStorer** [comment]
程序是直接在WSL2中安装依赖，但不会污染环境

目前的操作是，runner设置如果配置了国内源，则给WSL2设置国内apt源
如果没安装pip，则安装
如果没安装ninja，则安装
如果没安装cuda，则安装
接着安装torch, pytorch_lightning, deepspeed

无其他行为，也没有覆盖安装现象

**Comment by Mingzefei** [comment]
初步排查是 nvcc 和 gcc 版本问题，正在尝试解决。
从报错看，nvcc 至少应该高于 11.2，gcc 不应高于 6。 
我个人认为，尽管这个软件面向的人多数会有一个干净的 WSL2，但是软件直接在 WSL2 中安装依赖而不考虑环境隔离不是一个很好的选择。

**Comment by Mingzefei** [comment]
我放弃为这个WSL2匹配依赖，并在另外一台干净的电脑上正常运行。
这个 issue 应该没有再进行下去的必要，我关掉它吧。
