### ISSUE TITLE
[推理报错]双显卡自定义策略：cuda:0 fp16 *20 -> cuda:1 fp16 ,加载过程无报错，推理过程报错：RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument tensors in method wrapper_cat)

### ISSUE THREAD

**Issue by RuaYiii** [josStorer/RWKV-Runner#112]
所用的模型是RWKV-4-Raven-7B-v12  CN，两张RTX3080 ,再在单显卡的策略下无异常，使用自定义策略   `cuda:0 fp16 *20 -> cuda:1 fp16 `时，正常加载，但是使用时出现如下报错
**RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument tensors in method wrapper_cat)**

完整报错信息👇
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
File "D:\RWKV\py310\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 428, in run_asgi
result = await app(  # type: ignore[func-returns-value]
File "D:\RWKV\py310\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in **call**
return await self.app(scope, receive, send)
File "D:\RWKV\py310\Lib\site-packages\fastapi\[[applications.py](http://applications.py/)](http://applications.py/)", line 290, in **call**
await super().**call**(scope, receive, send)
File "D:\RWKV\py310\Lib\site-packages\starlette\[[applications.py](http://applications.py/)](http://applications.py/)", line 122, in **call**
await self.middleware_stack(scope, receive, send)
File "D:\RWKV\py310\Lib\site-packages\starlette\middleware\[[errors.py](http://errors.py/)](http://errors.py/)", line 184, in **call**
raise exc
File "D:\RWKV\py310\Lib\site-packages\starlette\middleware\[[errors.py](http://errors.py/)](http://errors.py/)", line 162, in **call**
await self.app(scope, receive, _send)
File "D:\RWKV\py310\Lib\site-packages\starlette\middleware\[[cors.py](http://cors.py/)](http://cors.py/)", line 91, in **call**
await self.simple_response(scope, receive, send, request_headers=headers)
File "D:\RWKV\py310\Lib\site-packages\starlette\middleware\[[cors.py](http://cors.py/)](http://cors.py/)", line 146, in simple_response
await self.app(scope, receive, send)
File "D:\RWKV\py310\Lib\site-packages\starlette\middleware\[[exceptions.py](http://exceptions.py/)](http://exceptions.py/)", line 79, in **call**
raise exc
File "D:\RWKV\py310\Lib\site-packages\starlette\middleware\[[exceptions.py](http://exceptions.py/)](http://exceptions.py/)", line 68, in **call**
await self.app(scope, receive, sender)
File "D:\RWKV\py310\Lib\site-packages\fastapi\middleware\[[asyncexitstack.py](http://asyncexitstack.py/)](http://asyncexitstack.py/)", line 20, in **call**
raise e
File "D:\RWKV\py310\Lib\site-packages\fastapi\middleware\[[asyncexitstack.py](http://asyncexitstack.py/)](http://asyncexitstack.py/)", line 17, in **call**
await self.app(scope, receive, send)
File "D:\RWKV\py310\Lib\site-packages\starlette\[[routing.py](http://routing.py/)](http://routing.py/)", line 718, in **call**
await route.handle(scope, receive, send)
File "D:\RWKV\py310\Lib\site-packages\starlette\[[routing.py](http://routing.py/)](http://[routing.py](http://routing.py/)/)", line 276, in handle
await self.app(scope, receive, send)
File "D:\RWKV\py310\Lib\site-packages\starlette\[routing.py](http://routing.py/)", line 69, in app
await response(scope, receive, send)
File "D:\RWKV\py310\Lib\site-packages\sse_starlette\[[sse.py](http://sse.py/)](http://sse.py/)", line 237, in **call**
async with anyio.create_task_group() as task_group:
File "D:\RWKV\py310\Lib\site-packages\anyio\_backends\_asyncio.py", line 597, in **aexit**
raise exceptions[0]
File "D:\RWKV\py310\Lib\site-packages\sse_starlette\[[sse.py](http://sse.py/)](http://[sse.py](http://sse.py/)/)", line 240, in wrap
await func()
File "D:\RWKV\py310\Lib\site-packages\sse_starlette\[sse.py](http://sse.py/)", line 225, in stream_response
async for data in self.body_iterator:
File "D:\RWKV\backend-python\routes\[[completion.py](http://completion.py/)](http://completion.py/)", line 112, in eval_rwkv
for response, delta, prompt_tokens, completion_tokens in model.generate(
File "D:\RWKV\backend-python\utils\[[rwkv.py](http://rwkv.py/)](http://[rwkv.py](http://rwkv.py/)/)", line 284, in generate
logits, prompt_token_len = self.run_rnn(
File "D:\RWKV\backend-python\utils\[rwkv.py](http://rwkv.py/)", line 102, in run_rnn
out, self.model_state = self.model.forward(
File "D:\RWKV\py310\Lib\site-packages\rwkv\[[model.py](http://model.py/)](http://model.py/)", line 672, in forward
x, state[i*5+0], state[i*5+1], state[i*5+2], state[i*5+3] = ATT(
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
File "D:\RWKV\py310\Lib\site-packages\rwkv\[[model.py](http://model.py/)](http://model.py/)", line 508, in att_seq
def att_seq(self, x, sx, aa, bb, pp, ln_w, ln_b, k_mix, v_mix, r_mix, t_decay, t_first, kw, vw, rw, ow, kmx, krx, kmy, kry, vmx, vrx, vmy, vry, rmx, rrx, rmy, rry, omx, orx, omy, ory):
xx = F.layer_norm(x, (x.shape[-1],), weight=ln_w, bias=ln_b)
sx = torch.cat((sx.unsqueeze(0), xx[:-1,:]))
~~~~~~~~~ <--- HERE
kx = xx * k_mix + sx * (1 - k_mix)
vx = xx * v_mix + sx * (1 - v_mix)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument tensors in method wrapper_cat)
```

**Comment by josStorer** [comment]
关掉自定义算子

**Comment by RuaYiii** [comment]
> 关掉自定义算子

关闭后依旧报错
```
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
File "D:\RWKV\py310\Lib\site-packages\rwkv\[model.py](http:model.py/)", line 508, in att_seq
def att_seq(self, x, sx, aa, bb, pp, ln_w, ln_b, k_mix, v_mix, r_mix, t_decay, t_first, kw, vw, rw, ow, kmx, krx, kmy, kry, vmx, vrx, vmy, vry, rmx, rrx, rmy, rry, omx, orx, omy, ory):
xx = F.layer_norm(x, (x.shape[-1],), weight=ln_w, bias=ln_b)
sx = torch.cat((sx.unsqueeze(0), xx[:-1,:]))
~~~~~~~~~ <--- HERE
kx = xx * k_mix + sx * (1 - k_mix)
vx = xx * v_mix + sx * (1 - v_mix)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument tensors in method wrapper_cat)
```
启动是能启动的，就是
![image](https://github.com/josStorer/RWKV-Runner/assets/35581454/338107de-c193-4bb4-a372-5057e8751baf)

**Comment by josStorer** [comment]
临时解决方法，程序启动后，在程序所在目录，执行
`./py310/python.exe -m pip uninstall cyac`
这会禁用内部state缓存，避免设备间数据拷贝

**Comment by RuaYiii** [comment]
> 临时解决方法，程序启动后，在程序所在目录，执行 `./py310/python.exe -m pip uninstall cyac` 这会禁用内部state缓存，避免设备间数据拷贝 由于程序启动后会自动释放cyac库，因此每次启动后都要执行一次，后续修复

尝试了一下，起效了👍
感谢

**Comment by josStorer** [comment]
许久前的版本已修复
