### ISSUE TITLE
出错，配置是3060 6g显存 模型为RWKV-4-Raven-7B-v11-Eng49%-Chn49%-Jpn1%-Other1%-20230430-ctx8192

### ISSUE THREAD

**Issue by burnedraven** [josStorer/RWKV-Runner#13]
错误信息如下：
INFO:     Started server process [22260]
INFO:     Waiting for application startup.
torch found: D:\LLM\py310\Lib\site-packages\torch\lib
torch set
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:63563 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:63563 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:63563 - "GET /status HTTP/1.1" 200 OK
INFO:     127.0.0.1:63563 - "OPTIONS /update-config HTTP/1.1" 200 OK
INFO:     127.0.0.1:63564 - "OPTIONS /switch-model HTTP/1.1" 200 OK
max_tokens=4100 temperature=1.2 top_p=0.5 presence_penalty=0.4 frequency_penalty=0.4
INFO:     127.0.0.1:63564 - "POST /update-config HTTP/1.1" 200 OK
RWKV_JIT_ON 1 RWKV_CUDA_ON 0 RESCALE_LAYER 6

Loading models/RWKV-4-Raven-7B-v11-Eng49%-Chn49%-Jpn1%-Other1%-20230430-ctx8192.pth ...
Strategy: (total 32+1=33 layers)
* cuda [float16, uint8], store 8 layers, stream 25 layers
0-cuda-float16-uint8 1-cuda-float16-uint8 2-cuda-float16-uint8 3-cuda-float16-uint8 4-cuda-float16-uint8 5-cuda-float16-uint8 6-cuda-float16-uint8 7-cuda-float16-uint8 8-cuda-float16-uint8-stream 9-cuda-float16-uint8-stream 10-cuda-float16-uint8-stream 11-cuda-float16-uint8-stream 12-cuda-float16-uint8-stream 13-cuda-float16-uint8-stream 14-cuda-float16-uint8-stream 15-cuda-float16-uint8-stream 16-cuda-float16-uint8-stream 17-cuda-float16-uint8-stream 18-cuda-float16-uint8-stream 19-cuda-float16-uint8-stream 20-cuda-float16-uint8-stream 21-cuda-float16-uint8-stream 22-cuda-float16-uint8-stream 23-cuda-float16-uint8-stream 24-cuda-float16-uint8-stream 25-cuda-float16-uint8-stream 26-cuda-float16-uint8-stream 27-cuda-float16-uint8-stream 28-cuda-float16-uint8-stream 29-cuda-float16-uint8-stream 30-cuda-float16-uint8-stream 31-cuda-float16-uint8-stream 32-cuda-float16-uint8-stream
emb.weight                        f16      cpu  50277  4096
blocks.0.ln1.weight               f16   cuda:0   4096
blocks.0.ln1.bias                 f16   cuda:0   4096
blocks.0.ln2.weight               f16   cuda:0   4096
blocks.0.ln2.bias                 f16   cuda:0   4096
blocks.0.att.time_decay           f32   cuda:0   4096
blocks.0.att.time_first           f32   cuda:0   4096
blocks.0.att.time_mix_k           f16   cuda:0   4096
blocks.0.att.time_mix_v           f16   cuda:0   4096
blocks.0.att.time_mix_r           f16   cuda:0   4096
blocks.0.att.key.weight            i8   cuda:0   4096  4096
blocks.0.att.value.weight          i8   cuda:0   4096  4096
blocks.0.att.receptance.weight     i8   cuda:0   4096  4096
blocks.0.att.output.weight         i8   cuda:0   4096  4096
blocks.0.ffn.time_mix_k           f16   cuda:0   4096
blocks.0.ffn.time_mix_r           f16   cuda:0   4096
blocks.0.ffn.key.weight            i8   cuda:0   4096 16384
blocks.0.ffn.receptance.weight     i8   cuda:0   4096  4096
blocks.0.ffn.value.weight          i8   cuda:0  16384  4096
...............................................................................................................................................................................................................................................................................................................[enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 268435456 bytes.
INFO:     127.0.0.1:63563 - "POST /switch-model HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\LLM\backend-python\routes\config.py", line 36, in switch_model
    RWKV(
  File "pydantic\main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic\main.py", line 1102, in pydantic.main.validate_model
  File "D:\LLM\py310\Lib\site-packages\langchain\llms\rwkv.py", line 119, in validate_environment
    values["client"] = RWKVMODEL(
  File "D:\LLM\py310\Lib\site-packages\torch\jit\_script.py", line 293, in init_then_script
    original_init(self, *args, **kwargs)
  File "D:\LLM\py310\Lib\site-packages\rwkv\model.py", line 308, in __init__
    w[x] = torch.clip(torch.floor(w[x] * 256), min=0, max=255).to(dtype=torch.uint8)
RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 268435456 bytes.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\LLM\py310\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\LLM\py310\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "D:\LLM\py310\Lib\site-packages\fastapi\applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "D:\LLM\py310\Lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\LLM\py310\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\LLM\py310\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\LLM\py310\Lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "D:\LLM\py310\Lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "D:\LLM\py310\Lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\LLM\py310\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\LLM\py310\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "D:\LLM\py310\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "D:\LLM\py310\Lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "D:\LLM\py310\Lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\LLM\py310\Lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "D:\LLM\py310\Lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "D:\LLM\py310\Lib\site-packages\fastapi\routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "D:\LLM\py310\Lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "D:\LLM\py310\Lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\LLM\py310\Lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\LLM\py310\Lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\LLM\backend-python\routes\config.py", line 45, in switch_model
    raise HTTPException(status.HTTP_500_INTERNAL_SERVER_ERROR, "failed to load")
AttributeError: 'function' object has no attribute 'HTTP_500_INTERNAL_SERVER_ERROR'

**Comment by josStorer** [comment]
not enough memory: you tried to allocate 268435456 bytes.，内存不够用于量化，增加虚拟内存，退出占内存的程序，或者用3B模型，一般来说16G内存是能完成量化的，你要关点程序

**Comment by burnedraven** [comment]
3b版确实可以用了，谢谢

**Comment by burnedraven** [comment]
3b版确实可以用了，谢谢
