### ISSUE TITLE
MetaGpt使用api报错500 Internal Server Error

### ISSUE THREAD

**Issue by lujunjiehhh** [josStorer/RWKV-Runner#168]
![image](https://github.com/josStorer/RWKV-Runner/assets/49628289/7264d8c1-b034-4167-bb3f-ec7309d1cc51)
#153 解决但是出现新的错误。
报错堆栈如下
INFO:     127.0.0.1:60094 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\RWKV\py310\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\RWKV\py310\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "D:\RWKV\py310\Lib\site-packages\fastapi\applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "D:\RWKV\py310\Lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\RWKV\py310\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\RWKV\py310\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\RWKV\py310\Lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "D:\RWKV\py310\Lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\RWKV\py310\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\RWKV\py310\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "D:\RWKV\py310\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "D:\RWKV\py310\Lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "D:\RWKV\py310\Lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\RWKV\py310\Lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "D:\RWKV\py310\Lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "D:\RWKV\py310\Lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "D:\RWKV\backend-python\routes\completion.py", line 306, in chat_completions
    body.stop.append(f"\n\n{user}")
AttributeError: 'NoneType' object has no attribute 'append'

**Comment by josStorer** [comment]
一个bug，后续修复，目前你可以通过不传递stop参数来解决
