### ISSUE TITLE
Python依赖缺失, 是否安装?

### ISSUE THREAD

**Issue by lampcccc** [josStorer/RWKV-Runner#181]
DepCheck Error: Traceback (most recent call last): File "C:\Users\one\Desktop\RWKV-Runner_windows_x64\backend-python\dep_check.py", line 13, in <module> import tokenizers File "C:\Users\one\Desktop\RWKV-Runner_windows_x64\py310\Lib\site-packages\tokenizers\__init__.py", line 80, in <module> from .tokenizers import ( ModuleNotFoundError: No module named 'tokenizers.tokenizers'

挂梯子没用
清华大学Pip镜像源没用
pip install tokenizers 没用 
Requirement already satisfied: tokenizers in c:\python311\lib\site-packages (0.13.3)

**Comment by lampcccc** [comment]
下的是这个https://github.com/josStorer/RWKV-Runner/releases/download/v1.4.5/RWKV-Runner_windows_x64.exe

**Comment by lampcccc** [comment]
MIDI-LLM-tokenizer

Desktop\RWKV-Runner_windows_x64\MIDI-LLM-tokenizer-main>python ./build_tokenizer.py
Traceback (most recent call last):
  File "C:\Users\one\Desktop\RWKV-Runner_windows_x64\MIDI-LLM-tokenizer-main\build_tokenizer.py", line 8, in <module>
    from transformers import PreTrainedTokenizerFast
ModuleNotFoundError: No module named 'transformers'

**Comment by lampcccc** [comment]
RWKV-Runner_windows_x64\py310\Lib\site-packages\tokenizers\__init__.py


第 80 行

from .tokenizers import (
    AddedToken,
    Encoding,
    NormalizedString,
    PreTokenizedString,
    Regex,
    Token,
    Tokenizer,
    decoders,
    models,
    normalizers,
    pre_tokenizers,
    processors,
    trainers,
)

**Comment by lampcccc** [comment]
![屏幕截图 2023-09-05 161852](https://github.com/josStorer/RWKV-Runner/assets/129349778/887b9b32-f4e5-4af3-9d15-f703d00eabfa)

**Comment by lampcccc** [comment]
更新解决
