### ISSUE TITLE
一些关于在linux服务器部署的问题

### ISSUE THREAD

**Issue by IMBAepsilon** [josStorer/RWKV-Runner#237]
执行 `python ./backend-python/main.py --port 6006 --webui`

`
Traceback (most recent call last):
  File "./backend-python/main.py", line 109, in <module>
    from webui_server import webui_server
  File "/root/RWKV-Runner/backend-python/webui_server.py", line 10, in <module>
    "/", StaticFiles(directory="frontend/dist", html=True), name="static"
  File "/root/miniconda3/lib/python3.8/site-packages/starlette/staticfiles.py", line 57, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
RuntimeError: Directory 'frontend/dist' does not exist
`

发现好像没找到哪里是和这个 'frontend/dist'  相关的

**Comment by josStorer** [comment]
GUI训练目前只支持windows本地进行, 不支持服务器, 在线实时训练可以试试这个项目: https://github.com/neromous/RWKV-Ouroboros

设置的API URL只支持使用推理功能, 不支持调用远程的下载, 配置, 训练

前端构建执行make build-web

**Comment by IMBAepsilon** [comment]
> GUI训练目前只支持windows本地进行, 不支持服务器, 在线实时训练可以试试这个项目: https://github.com/neromous/RWKV-Ouroboros
> 
> 设置的API URL只支持使用推理功能, 不支持调用远程的下载, 配置, 训练
> 
> 前端构建执行make build-web

好的，我研究了一下在线训练，有了一定收获。
但是现在还有一个问题，我似乎还是没有办法远程进行推理。我填写API之后点生成还是提示没有运行模型，而运行模型会提示本地没有模型

**Comment by eyaeya** [comment]
> 执行 python ./backend-python/main.py --port 6006 --webui
> 发现好像没找到哪里是和这个 'frontend/dist' 相关的


#### 情况一：
这个问题源于你未编译前端，如果仅后端运行，请删除参数 `--webui`。或者先完成前端编译。

#### 情况二：
这个问题源于命令行的起始目录不对，请 `cd` 到 RWKV-Runner 目录下，再执行 `python ./backend-python/main.py --port 6006 --webui`

**Comment by jjiikkkk** [comment]
> > 执行 python ./backend-python/main.py --port 6006 --webui
> > 发现好像没找到哪里是和这个 'frontend/dist' 相关的
> 
> #### 情况一：
> 这个问题源于你未编译前端，如果仅后端运行，请删除参数 `--webui`。或者先完成前端编译。
> 
> #### 情况二：
> 这个问题源于命令行的起始目录不对，请 `cd` 到 RWKV-Runner 目录下，再执行 `python ./backend-python/main.py --port 6006 --webui`

这个linux写的真的太乱了

**Comment by jjiikkkk** [comment]
> Traceback (most recent call last):
>   File "./backend-python/main.py", line 109, in <module>
>     from webui_server import webui_server
>   File "/root/RWKV-Runner/backend-python/webui_server.py", line 10, in <module>
>     "/", StaticFiles(directory="frontend/dist", html=True), name="static"
>   File "/root/miniconda3/lib/python3.8/site-packages/starlette/staticfiles.py", line 57, in __init__
>     raise RuntimeError(f"Directory '{directory}' does not exist")
> RuntimeError: Directory 'frontend/dist' does not exist

Traceback (most recent call last):
  File "./backend-python/main.py", line 109, in <module>
    from webui_server import webui_server
  File "/root/RWKV-Runner/backend-python/webui_server.py", line 10, in <module>
    "/", StaticFiles(directory="frontend/dist", html=True), name="static"
  File "/root/miniconda3/lib/python3.8/site-packages/starlette/staticfiles.py", line 57, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
RuntimeError: Directory 'frontend/dist' does not exist  这个是makefile的那个问题是吗，哎 好混乱 乱的真的是

**Comment by jjiikkkk** [comment]
如果要编译 超级麻烦，又是go, 又是makefile，又是wails，为什么 不可以把所有内容 写一起呢，挤牙膏一样，一会一点点一会一点点

**Comment by josStorer** [comment]
@jjiikkkk 请不要在无关话题下刷屏发泄情绪, 我已经在 #257 对你的问题进行了回应, 如果你看不懂, 可以把我的话发给chatgpt, 让它解释

**Comment by jjiikkkk** [comment]
我也没那么差吧 还是懂点的，老是试不通，头疼
空了继续测试 ：（
