### ISSUE TITLE
Linux 下使用 rwkv.cpp 推理 `Failed to find librwkv.so automatically`

### ISSUE THREAD

**Issue by PJ-568** [josStorer/RWKV-Runner#242]
启动：
```shell
python3 /home/usrnm/prog/RWKV-Runner/backend-python/main.py --rwkv.cpp > log.txt
```
载入模型：
```shell
curl http://127.0.0.1:8000/switch-model -X POST -H "Content-Type: application/json" -d '{"model":"/home/usrnm/prog/RWKV-Runner/models/RWKV-5-World-0.1B-v1-20230803-ctx4096-fp16.bin","strategy":"cpu fp32"}'

{"detail":"failed to load: Failed to find librwkv.so automatically; you need to find the library and create RWKVSharedLibrary specifying the path to it"}
```
客户端尝试 Chat 后返回：
```json
{
  "detail": "model not loaded"
}
```
log：
```
--- 5.6035778522491455 seconds ---
cyac not found
torch found: /usr/lib/python3.11/site-packages/torch/lib
torch set
Strategy Devices: {'cpu'}
state cache disabled
Using rwkv.cpp, strategy is ignored
Failed to find librwkv.so automatically; you need to find the library and create RWKVSharedLibrary specifying the path to it
Traceback (most recent call last):
  File "/home/pj568/文档/RWKV-Runner/backend-python/routes/config.py", line 73, in switch_model
    RWKV(model=body.model, strategy=body.strategy, tokenizer=body.tokenizer),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pj568/文档/RWKV-Runner/backend-python/utils/rwkv.py", line 536, in RWKV
    model = Model(model, strategy)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pj568/文档/RWKV-Runner/backend-python/rwkv_pip/cpp/model.py", line 8, in __init__
    self.library = rwkv_cpp_shared_library.load_rwkv_shared_library()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pj568/文档/RWKV-Runner/backend-python/rwkv_pip/cpp/rwkv_cpp_shared_library.py", line 443, in load_rwkv_shared_library
    assert False, (f'Failed to find {file_name} automatically; '
AssertionError: Failed to find librwkv.so automatically; you need to find the library and create RWKVSharedLibrary specifying the path to it

INFO:     127.0.0.1:52322 - "POST /switch-model HTTP/1.1" 500 Internal Server Error
INFO:     2a06:98c0:3600::103:0 - "POST /v1/chat/completions?path=v1%2Fchat%2Fcompletions HTTP/1.1" 400 Bad Request
INFO:     2a06:98c0:3600::103:0 - "POST /v1/chat/completions?path=v1%2Fchat%2Fcompletions HTTP/1.1" 400 Bad Request
```

**Comment by josStorer** [comment]
cd到RWKV-Runner的目录下再运行看看

**Comment by PJ-568** [comment]
仍不行。

启动：
```shell
cd /home/usrnm/prog/RWKV-Runner/
python3 ./backend-python/main.py --rwkv.cpp > log.txt
```
载入模型：
```shell
cd /home/usrnm/prog/RWKV-Runner/
curl http://127.0.0.1:8000/switch-model -X POST -H "Content-Type: application/json" -d '{"model":"./models/RWKV-5-World-0.1B-v1-20230803-ctx4096-fp16.bin","strategy":"cpu fp32"}'

curl: (52) Empty reply from server
```
客户端尝试 Chat 后返回：
```json
{
  "error": true,
  "message": "NetworkError when attempting to fetch resource."
}
```
log：
```
--- 5.6035778522491455 seconds ---
cyac not found
torch found: /usr/lib/python3.11/site-packages/torch/lib
torch set
Strategy Devices: {'cpu'}
state cache disabled
Using rwkv.cpp, strategy is ignored
Failed to find librwkv.so automatically; you need to find the library and create RWKVSharedLibrary specifying the path to it
Traceback (most recent call last):
  File "/home/usrnm/prog/RWKV-Runner/backend-python/routes/config.py", line 73, in switch_model
    RWKV(model=body.model, strategy=body.strategy, tokenizer=body.tokenizer),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usrnm/prog/RWKV-Runner/backend-python/utils/rwkv.py", line 536, in RWKV
    model = Model(model, strategy)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usrnm/prog/RWKV-Runner/backend-python/rwkv_pip/cpp/model.py", line 8, in __init__
    self.library = rwkv_cpp_shared_library.load_rwkv_shared_library()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usrnm/prog/RWKV-Runner/backend-python/rwkv_pip/cpp/rwkv_cpp_shared_library.py", line 443, in load_rwkv_shared_library
    assert False, (f'Failed to find {file_name} automatically; '
AssertionError: Failed to find librwkv.so automatically; you need to find the library and create RWKVSharedLibrary specifying the path to it

INFO:     127.0.0.1:52322 - "POST /switch-model HTTP/1.1" 500 Internal Server Error
INFO:     2a06:98c0:3600::103:0 - "POST /v1/chat/completions?path=v1%2Fchat%2Fcompletions HTTP/1.1" 400 Bad Request
INFO:     2a06:98c0:3600::103:0 - "POST /v1/chat/completions?path=v1%2Fchat%2Fcompletions HTTP/1.1" 400 Bad Request
INFO:     2a06:98c0:3600::103:0 - "GET / HTTP/1.1" 200 OK
INFO:     2a06:98c0:3600::103:0 - "GET / HTTP/1.1" 200 OK
INFO:     2a06:98c0:3600::103:0 - "GET / HTTP/1.1" 200 OK
INFO:     2a06:98c0:3600::103:0 - "GET / HTTP/1.1" 200 OK
INFO:     2a06:98c0:3600::103:0 - "GET / HTTP/1.1" 200 OK
INFO:     213.180.203.99:0 - "GET /robots.txt HTTP/1.1" 404 Not Found
INFO:     213.180.203.73:0 - "GET / HTTP/1.1" 200 OK
INFO:     2a06:98c0:3600::103:0 - "GET / HTTP/1.1" 200 OK
```

**Comment by PJ-568** [comment]
我注意到在未运行 `curl http://127.0.0.1:8000/switch-model -X POST -H "Content-Type: application/json" -d '{"model":"./models/RWKV-5-World-0.1B-v1-20230803-ctx4096-fp16.bin","strategy":"cpu fp32"}'` 情况下 `./backend-python/main.py` 就已输出上述 log 。

**Comment by josStorer** [comment]
你用下screen或者tmux启动服务
