### ISSUE TITLE
Error: "AttributeError: 'MMapIndexedDataset' object has no attribute '_bin_buffer_mmap'"

### ISSUE THREAD

**Issue by mingcun693** [josStorer/RWKV-Runner#249]
I get this error when using the LoRA train:
```
[3/3] c++ wkv_op_bf16.o wkv_cuda_bf16.cuda.o -shared -L/usr/local/lib/python3.8/dist-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda_cu -ltorch_cuda_cpp -ltorch -ltorch_python -L/usr/local/cuda/lib64 -lcudart -o wkv_1024_bf16.so
Loading extension module wkv_1024_bf16...
Current vocab size = 50277 (make sure it's correct)
Traceback (most recent call last):
File "./finetune/lora/train.py", line 342, in <module>
train_data = MyDataset(args)
File "/mnt/d/x/rwkv-12/finetune/lora/src/dataset.py", line 31, in __init__
self.data = MMapIndexedDataset(args.data_file)
File "/mnt/d/x/rwkv-12/finetune/lora/src/binidx.py", line 179, in __init__
self._do_init(path, skip_warmup)
File "/mnt/d/x/rwkv-12/finetune/lora/src/binidx.py", line 195, in _do_init
self._bin_buffer_mmap = np.memmap(
File "/usr/lib/python3/dist-packages/numpy/core/memmap.py", line 264, in __new__
mm = mmap.mmap(fid.fileno(), bytes, access=acc, offset=start)
ValueError: cannot mmap an empty file
Exception ignored in: <function MMapIndexedDataset.__del__ at 0x7f61ba89ce50>
Traceback (most recent call last):
File "/mnt/d/x/rwkv-12/finetune/lora/src/binidx.py", line 202, in __del__
self._bin_buffer_mmap._mmap.close()
AttributeError: 'MMapIndexedDataset' object has no attribute '_bin_buffer_mmap'
```
Here is my software version:
- rwkv-runner 1.6.5 in Win10

**Comment by mingcun693** [comment]
Ops! I know it. 
The raw data is wrong.
Sorry.
