### ISSUE TITLE
启动模型后，模型不能正常输出

### ISSUE THREAD

**Issue by jang11441211** [josStorer/RWKV-Runner#261]
![1704945022821](https://github.com/josStorer/RWKV-Runner/assets/36251683/f3aec26a-1f49-42e7-aaa2-24ceae694a5b)
请问怎么处理这个问题？

**Comment by jang11441211** [comment]
```
head.weight                       f16   cuda:0   2048 65536
D:\RWKV\backend-python\rwkv_pip\model.py:1824: UserWarning: operator () profile_node %318 : int = prim::profile_ivalue(%316)
 does not have profile information (Triggered internally at ..\torch\csrc\jit\codegen\cuda\graph_fuser.cpp:109.)
  r, k, v, g, xxx, ss = self.v5_2_before(
INFO:     127.0.0.1:49843 - "POST /switch-model HTTP/1.1" 200 OK
INFO:     127.0.0.1:50019 - "OPTIONS /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:50019 - "POST /v1/chat/completions HTTP/1.1" 200 OK
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\RWKV\py310\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\RWKV\py310\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "D:\RWKV\py310\Lib\site-packages\fastapi\applications.py", line 1115, in __call__
    await super().__call__(scope, receive, send)
  File "D:\RWKV\py310\Lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\RWKV\py310\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\RWKV\py310\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\RWKV\py310\Lib\site-packages\starlette\middleware\cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "D:\RWKV\py310\Lib\site-packages\starlette\middleware\cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "D:\RWKV\py310\Lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\RWKV\py310\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\RWKV\py310\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "D:\RWKV\py310\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "D:\RWKV\py310\Lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "D:\RWKV\py310\Lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\RWKV\py310\Lib\site-packages\starlette\routing.py", line 69, in app
    await response(scope, receive, send)
  File "D:\RWKV\py310\Lib\site-packages\sse_starlette\sse.py", line 233, in __call__
    async with anyio.create_task_group() as task_group:
  File "D:\RWKV\py310\Lib\site-packages\anyio\_backends\_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "D:\RWKV\py310\Lib\site-packages\sse_starlette\sse.py", line 236, in wrap
    await func()
  File "D:\RWKV\py310\Lib\site-packages\sse_starlette\sse.py", line 221, in stream_response
    async for data in self.body_iterator:
  File "D:\RWKV\backend-python\routes\completion.py", line 149, in eval_rwkv
    for response, delta, prompt_tokens, completion_tokens in model.generate(
  File "D:\RWKV\backend-python\utils\rwkv.py", line 270, in generate
    token = self.pipeline.sample_logits(
  File "D:\RWKV\backend-python\rwkv_pip\utils.py", line 143, in sample_logits
    out = torch.multinomial(probs, num_samples=1)[0]
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
```

**Comment by josStorer** [comment]
配置页面截图看一下

**Comment by jang11441211** [comment]
![image](https://github.com/josStorer/RWKV-Runner/assets/36251683/0146cadd-a2f6-4aa5-bfb6-ddacc04e7846)

**Comment by josStorer** [comment]
什么显卡, 试试关掉自定义CUDA算子

**Comment by jang11441211** [comment]
显卡是1650，我关闭cuda后。可以正常输出了。谢谢您的帮助

**Comment by josStorer** [comment]
可以nvidia-smi看看驱动版本, 尝试更新驱动, 自定义算子能开最好开, 虽然1.5B不开速度也可以

**Comment by josStorer** [comment]
此外你可以试试WebGPU(Python)模式, 开nf4跑3B, 或许会比1.5B的效果更好
