### ISSUE TITLE
RWKV-Runner用不了wangwen-2022-02-15.pth模型

### ISSUE THREAD

**Issue by i3587616** [josStorer/RWKV-Runner#277]
我用这个exe选了wangwen-2022-02-15.pth这个模型就报错。
用RWKV-4-Pile-1B5-Chn-testNovel-done-ctx2048-20230312.pth没有错。
这个版本: 1.6.8的加载不了这个wangwen-2022-02-15.pth吗，
报错如下：
Loading ./models/wangwen-2022-02-15.pth ...
No module named 'src'
Traceback (most recent call last):
  File "G:\ai\backend-python\routes\config.py", line 73, in switch_model
    RWKV(model=body.model, strategy=body.strategy, tokenizer=body.tokenizer),
  File "G:\ai\backend-python\utils\rwkv.py", line 579, in RWKV
    model = Model(model, strategy)
  File "G:\ai\py310\Lib\site-packages\torch\jit\_script.py", line 303, in init_then_script
    original_init(self, *args, **kwargs)
  File "G:\ai\backend-python\rwkv_pip\beta\model.py", line 231, in __init__
    self.w = torch.load(
  File "G:\ai\py310\Lib\site-packages\torch\serialization.py", line 1026, in load
    return _load(opened_zipfile,
  File "G:\ai\py310\Lib\site-packages\torch\serialization.py", line 1438, in _load
    result = unpickler.load()
  File "G:\ai\py310\Lib\site-packages\torch\serialization.py", line 1431, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'src'

INFO:     127.0.0.1:57863 - "POST /switch-model HTTP/1.1" 500 Internal Server Error

**Comment by josStorer** [comment]
RWKV有很多版本, 本项目目前支持RWKV-4及以上版本的文本类模型和作曲类模型
可能是这个模型太老了, 本项目没有适配, 建议从模型页面下载更新的模型

https://github.com/BlinkDL/AI-Writer

**Comment by i3587616** [comment]
嗯，了解
