### ISSUE TITLE
bin模型无法加载

### ISSUE THREAD

**Issue by yuelangjun** [josStorer/RWKV-Runner#366]
D:\a\rwkv.cpp\rwkv.cpp\rwkv.cpp:65: rwkv_load_model_from_file(file_path, *ctx->model)
rwkv_init_from_file failed, check stderr
Traceback (most recent call last):
  File "D:\桌面\RWKV\backend-python\routes\config.py", line 73, in switch_model
    RWKV(model=body.model, strategy=body.strategy, tokenizer=body.tokenizer),
  File "D:\桌面\RWKV\backend-python\utils\rwkv.py", line 644, in RWKV
    model = Model(model_path, strategy)
  File "D:\桌面\RWKV\backend-python\rwkv_pip\cpp\model.py", line 9, in __init__
    self.model = rwkv_cpp_model.RWKVModel(self.library, model_path)
  File "D:\桌面\RWKV\backend-python\rwkv_pip\cpp\rwkv_cpp_model.py", line 66, in __init__
    self._ctx: rwkv_cpp_shared_library.RWKVContext = self._library.rwkv_init_from_file(model_path, thread_count)
  File "D:\桌面\RWKV\backend-python\rwkv_pip\cpp\rwkv_cpp_shared_library.py", line 146, in rwkv_init_from_file
    raise ValueError("rwkv_init_from_file failed, check stderr")
ValueError: rwkv_init_from_file failed, check stderr

INFO:     127.0.0.1:51884 - "POST /switch-model HTTP/1.1" 500 Internal Server Error

**Comment by josStorer** [comment]
重新转换一下模型试试

**Comment by shoumenchougou** [comment]
从  1.8.5 版本开始，RWKV Runner 的 rwkv.cpp 模式才支持 RWKV-6 架构模型，你可以检查一下是不是还没升级 RWKV Runner 的版本
