### ISSUE TITLE
运行后提示依赖缺失

### ISSUE THREAD

**Issue by xqingting** [josStorer/RWKV-Runner#392]
DepCheck Error: Traceback (most recent call last): File "D:\LLM\RWKV-Runner\backend-python\dep_check.py", line 20, in <module> import tokenizers File "D:\LLM\RWKV-Runner\py310\Lib\site-packages\tokenizers\__init__.py", line 78, in <module> from .tokenizers import ( ModuleNotFoundError: No module named 'tokenizers.tokenizers' GError: exit status 1

**Comment by xqingting** [comment]
强制重装后解决了

py310\python.exe -m pip install --force-reinstall -v "torch"
py310\python.exe -m pip install --force-reinstall -v "torchvision"
py310\python.exe -m pip install --force-reinstall -v "torchaudio"
py310\python.exe -m pip install --force-reinstall -v "setuptools==69.5.1"
py310\python.exe -m pip install --force-reinstall -v "rwkv==0.8.26"
py310\python.exe -m pip install --force-reinstall -v "langchain==0.0.322"
py310\python.exe -m pip install --force-reinstall -v "fastapi==0.109.1"
py310\python.exe -m pip install --force-reinstall -v "uvicorn==0.23.2"
py310\python.exe -m pip install --force-reinstall -v "sse-starlette==1.6.5"
py310\python.exe -m pip install --force-reinstall -v "pydantic==2.4.2"
py310\python.exe -m pip install --force-reinstall -v "psutil==5.9.6"
py310\python.exe -m pip install --force-reinstall -v "gputil==1.4.0"
py310\python.exe -m pip install --force-reinstall -v "tiktoken==0.5.1"
py310\python.exe -m pip install --force-reinstall -v "ftfy==6.1.1"
py310\python.exe -m pip install --force-reinstall -v "lm-dataformat==0.0.20"
py310\python.exe -m pip install --force-reinstall -v "numpy==1.24.4"
py310\python.exe -m pip install --force-reinstall -v "tokenizers==0.14.1"
py310\python.exe -m pip install --force-reinstall -v "tqdm==4.66.1"
py310\python.exe -m pip install --force-reinstall -v "midi2audio==0.1.1"
py310\python.exe -m pip install --force-reinstall -v "mido==1.3.0"
py310\python.exe -m pip install --force-reinstall -v "safetensors==0.4.0"
py310\python.exe -m pip install --force-reinstall -v "PyMuPDF==1.23.5"
py310\python.exe -m pip install --force-reinstall -v "python-multipart==0.0.7"
py310\python.exe -m pip install --force-reinstall -v "Cython==3.0.4"


现在是环境变量
CUDA_HOME environment variable is not set. Please set it to your CUDA install root."}
