### ISSUE TITLE
intel CPU Mac运行提示No module named 'GPUtil'

### ISSUE THREAD

**Issue by lietxia** [josStorer/RWKV-Runner#54]
macOS 13.4 (22F66)    
Python 3.11.3    
程序在`/Applications/RWKV/RWKV-Runner.app`  
已进入`/Applications/RWKV/`执行 `sudo xattr -r -d com.apple.quarantine ./RWKV-Runner.app`  
配置选择MAC-3B-CN后点运行
### 提示`Python依赖缺失, 是否安装?`
左下角为
```
DepCheck Error: Traceback (most recent call last): File "/Applications/RWKV/RWKV-Runner.app/Contents/MacOS/../../.././backend-python/dep_check.py", line 1, in <module> import GPUtil ModuleNotFoundError: No module named 'GPUtil'
```

### 点击【安装】后，出来3个终端窗口，内容分别为
```
Last login: Wed Jun  7 05:54:45 on ttys000
lietxia@LietXias-iMac ~ % cd /Applications/RWKV/RWKV-Runner.app/Contents/MacOS/../../../ && python3 ./backend-python/get-pip.py -i https://pypi.tuna.tsinghua.edu.cn/simple
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting pip
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/08/e3/57d4c24a050aa0bcca46b2920bff40847db79535dc78141eb83581a52eb8/pip-23.1.2-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 23.1.2
    Uninstalling pip-23.1.2:
      Successfully uninstalled pip-23.1.2
Successfully installed pip-23.1.2
lietxia@LietXias-iMac RWKV % 
```

```
Last login: Wed Jun  7 06:00:17 on ttys001
cd /Applications/RWKV/RWKV-Runner.app/Contents/MacOS/../../../ && python3 -m pip install torch torchvision torchaudio
lietxia@LietXias-iMac ~ % cd /Applications/RWKV/RWKV-Runner.app/Contents/MacOS/../../../ && python3 -m pip install torch torchvision torchaudio
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: torch in /usr/local/lib/python3.11/site-packages (2.0.1)
Requirement already satisfied: torchvision in /usr/local/lib/python3.11/site-packages (0.15.2)
Requirement already satisfied: torchaudio in /usr/local/lib/python3.11/site-packages (2.0.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/site-packages (from torch) (3.12.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.11/site-packages (from torch) (4.5.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.11/site-packages (from torch) (1.12)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/site-packages (from torch) (3.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/site-packages (from torch) (3.1.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/site-packages (from torchvision) (1.24.3)
Requirement already satisfied: requests in /usr/local/lib/python3.11/site-packages (from torchvision) (2.30.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.11/site-packages (from torchvision) (9.5.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/site-packages (from jinja2->torch) (2.1.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/site-packages (from requests->torchvision) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/site-packages (from requests->torchvision) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/site-packages (from requests->torchvision) (2.0.2)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/site-packages (from requests->torchvision) (2023.5.7)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.11/site-packages (from sympy->torch) (1.3.0)
lietxia@LietXias-iMac RWKV % 
```

```
Last login: Wed Jun  7 06:00:17 on ttys002
cd /Applications/RWKV/RWKV-Runner.app/Contents/MacOS/../../../ && python3 -m pip install -r ./backend-python/requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
lietxia@LietXias-iMac ~ % cd /Applications/RWKV/RWKV-Runner.app/Contents/MacOS/../../../ && python3 -m pip install -r ./backend-python/requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: torch in /usr/local/lib/python3.11/site-packages (from -r ./backend-python/requirements.txt (line 1)) (2.0.1)
Requirement already satisfied: rwkv in /usr/local/lib/python3.11/site-packages (from -r ./backend-python/requirements.txt (line 2)) (0.7.3)
Requirement already satisfied: langchain in /usr/local/lib/python3.11/site-packages (from -r ./backend-python/requirements.txt (line 3)) (0.0.166)
Requirement already satisfied: fastapi in /usr/local/lib/python3.11/site-packages (from -r ./backend-python/requirements.txt (line 4)) (0.95.1)
Requirement already satisfied: uvicorn in /usr/local/lib/python3.11/site-packages (from -r ./backend-python/requirements.txt (line 5)) (0.22.0)
Requirement already satisfied: sse-starlette in /usr/local/lib/python3.11/site-packages (from -r ./backend-python/requirements.txt (line 6)) (1.5.0)
Requirement already satisfied: pydantic in /usr/local/lib/python3.11/site-packages (from -r ./backend-python/requirements.txt (line 7)) (1.10.7)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/site-packages (from -r ./backend-python/requirements.txt (line 8)) (5.9.5)
Requirement already satisfied: gputil in /usr/local/lib/python3.11/site-packages (from -r ./backend-python/requirements.txt (line 9)) (1.4.0)
Requirement already satisfied: cyac in /usr/local/lib/python3.11/site-packages (from -r ./backend-python/requirements.txt (line 10)) (1.7)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/site-packages (from torch->-r ./backend-python/requirements.txt (line 1)) (3.12.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.11/site-packages (from torch->-r ./backend-python/requirements.txt (line 1)) (4.5.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.11/site-packages (from torch->-r ./backend-python/requirements.txt (line 1)) (1.12)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/site-packages (from torch->-r ./backend-python/requirements.txt (line 1)) (3.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/site-packages (from torch->-r ./backend-python/requirements.txt (line 1)) (3.1.2)
Requirement already satisfied: tokenizers>=0.13.2 in /usr/local/lib/python3.11/site-packages (from rwkv->-r ./backend-python/requirements.txt (line 2)) (0.13.3)
Requirement already satisfied: PyYAML>=5.4.1 in /usr/local/lib/python3.11/site-packages (from langchain->-r ./backend-python/requirements.txt (line 3)) (6.0)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in /usr/local/lib/python3.11/site-packages (from langchain->-r ./backend-python/requirements.txt (line 3)) (2.0.13)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.11/site-packages (from langchain->-r ./backend-python/requirements.txt (line 3)) (3.8.4)
Requirement already satisfied: dataclasses-json<0.6.0,>=0.5.7 in /usr/local/lib/python3.11/site-packages (from langchain->-r ./backend-python/requirements.txt (line 3)) (0.5.7)
Requirement already satisfied: numexpr<3.0.0,>=2.8.4 in /usr/local/lib/python3.11/site-packages (from langchain->-r ./backend-python/requirements.txt (line 3)) (2.8.4)
Requirement already satisfied: numpy<2,>=1 in /usr/local/lib/python3.11/site-packages (from langchain->-r ./backend-python/requirements.txt (line 3)) (1.24.3)
Requirement already satisfied: openapi-schema-pydantic<2.0,>=1.2 in /usr/local/lib/python3.11/site-packages (from langchain->-r ./backend-python/requirements.txt (line 3)) (1.2.4)
Requirement already satisfied: requests<3,>=2 in /usr/local/lib/python3.11/site-packages (from langchain->-r ./backend-python/requirements.txt (line 3)) (2.30.0)
Requirement already satisfied: tenacity<9.0.0,>=8.1.0 in /usr/local/lib/python3.11/site-packages (from langchain->-r ./backend-python/requirements.txt (line 3)) (8.2.2)
Requirement already satisfied: tqdm>=4.48.0 in /usr/local/lib/python3.11/site-packages (from langchain->-r ./backend-python/requirements.txt (line 3)) (4.65.0)
Requirement already satisfied: starlette<0.27.0,>=0.26.1 in /usr/local/lib/python3.11/site-packages (from fastapi->-r ./backend-python/requirements.txt (line 4)) (0.26.1)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.11/site-packages (from uvicorn->-r ./backend-python/requirements.txt (line 5)) (8.1.3)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.11/site-packages (from uvicorn->-r ./backend-python/requirements.txt (line 5)) (0.14.0)
Requirement already satisfied: cython>=0.29.0 in /usr/local/lib/python3.11/site-packages (from cyac->-r ./backend-python/requirements.txt (line 10)) (0.29.34)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain->-r ./backend-python/requirements.txt (line 3)) (23.1.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in /usr/local/lib/python3.11/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain->-r ./backend-python/requirements.txt (line 3)) (3.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain->-r ./backend-python/requirements.txt (line 3)) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /usr/local/lib/python3.11/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain->-r ./backend-python/requirements.txt (line 3)) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.11/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain->-r ./backend-python/requirements.txt (line 3)) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain->-r ./backend-python/requirements.txt (line 3)) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain->-r ./backend-python/requirements.txt (line 3)) (1.3.1)
Requirement already satisfied: marshmallow<4.0.0,>=3.3.0 in /usr/local/lib/python3.11/site-packages (from dataclasses-json<0.6.0,>=0.5.7->langchain->-r ./backend-python/requirements.txt (line 3)) (3.19.0)
Requirement already satisfied: marshmallow-enum<2.0.0,>=1.5.1 in /usr/local/lib/python3.11/site-packages (from dataclasses-json<0.6.0,>=0.5.7->langchain->-r ./backend-python/requirements.txt (line 3)) (1.5.1)
Requirement already satisfied: typing-inspect>=0.4.0 in /usr/local/lib/python3.11/site-packages (from dataclasses-json<0.6.0,>=0.5.7->langchain->-r ./backend-python/requirements.txt (line 3)) (0.8.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/site-packages (from requests<3,>=2->langchain->-r ./backend-python/requirements.txt (line 3)) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/site-packages (from requests<3,>=2->langchain->-r ./backend-python/requirements.txt (line 3)) (2.0.2)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/site-packages (from requests<3,>=2->langchain->-r ./backend-python/requirements.txt (line 3)) (2023.5.7)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.11/site-packages (from SQLAlchemy<3,>=1.4->langchain->-r ./backend-python/requirements.txt (line 3)) (2.0.2)
Requirement already satisfied: anyio<5,>=3.4.0 in /usr/local/lib/python3.11/site-packages (from starlette<0.27.0,>=0.26.1->fastapi->-r ./backend-python/requirements.txt (line 4)) (3.6.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/site-packages (from jinja2->torch->-r ./backend-python/requirements.txt (line 1)) (2.1.2)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.11/site-packages (from sympy->torch->-r ./backend-python/requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/site-packages (from anyio<5,>=3.4.0->starlette<0.27.0,>=0.26.1->fastapi->-r ./backend-python/requirements.txt (line 4)) (1.3.0)
Requirement already satisfied: packaging>=17.0 in /usr/local/lib/python3.11/site-packages (from marshmallow<4.0.0,>=3.3.0->dataclasses-json<0.6.0,>=0.5.7->langchain->-r ./backend-python/requirements.txt (line 3)) (23.1)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.11/site-packages (from typing-inspect>=0.4.0->dataclasses-json<0.6.0,>=0.5.7->langchain->-r ./backend-python/requirements.txt (line 3)) (1.0.0)
WARNING: Ignoring invalid distribution ~ip (/usr/local/lib/python3.11/site-packages)
WARNING: Ignoring invalid distribution ~ip (/usr/local/lib/python3.11/site-packages)
WARNING: Ignoring invalid distribution ~ip (/usr/local/lib/python3.11/site-packages)
lietxia@LietXias-iMac RWKV %
```

程序好像在调用系统python，手动执行`python3 -m pip install GPUtil`  
依旧提示缺少GPUtil

**Comment by josStorer** [comment]
Not sure if this only happens on intel cpu macs, I tested on m1 macs with no issues

**Comment by lietxia** [comment]
> I had the same problem, my solution was to install all requirements using python3 -m pip install then go to RWKV -> setting -> advance -> python path -> type: python3
thanks! It worked.
RWKV -> setting -> advance -> python path ->`/usr/local/bin/python3`

**Comment by josStorer** [comment]
For anyone has the same issue, use `which python3` to locate your python path, and fill it in `Settings -> Custom Python Path`

**Comment by SunNate** [comment]
Could not import runpy module
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1170, in exec_module
  File "<frozen runpy>", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1316, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1256, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1524, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1498, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1601, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1644, in _fill_cache
OSError: [Errno 34] Result too large: '/private/var/folders/fr/y_d_kj3121j64d3sjn6msvrr0000gn/T/AppTranslocation/24A860EB-E8D6-43DE-8082-99A792818E7F/d'

macos，m系列处理
这种情况怎么解决？

**Comment by josStorer** [comment]
@SunNate 程序放在桌面, 或者文稿, 或者下载目录, 自己建个空文件夹

**Comment by nonotouchtouch** [comment]
缺少依赖的问题可以使用以下解决方法：
先运行命令 which python3，复制输出结果，粘贴到程序左下角设置--高级--自定义python路径
重新安装依赖即可
