### ISSUE TITLE
运行中不再输出，窗口提示错误信息，是否是输出内容太多导致，等了很久也不行

### ISSUE THREAD

**Issue by zmengle** [josStorer/RWKV-Runner#59]
报错信息
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "F:\video\rwkv\py310\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "F:\video\rwkv\py310\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "F:\video\rwkv\py310\Lib\site-packages\fastapi\applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "F:\video\rwkv\py310\Lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "F:\video\rwkv\py310\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "F:\video\rwkv\py310\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "F:\video\rwkv\py310\Lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "F:\video\rwkv\py310\Lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "F:\video\rwkv\py310\Lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "F:\video\rwkv\py310\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "F:\video\rwkv\py310\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "F:\video\rwkv\py310\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "F:\video\rwkv\py310\Lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "F:\video\rwkv\py310\Lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "F:\video\rwkv\py310\Lib\site-packages\starlette\routing.py", line 69, in app
    await response(scope, receive, send)
  File "F:\video\rwkv\py310\Lib\site-packages\sse_starlette\sse.py", line 232, in __call__
    async with anyio.create_task_group() as task_group:
  File "F:\video\rwkv\py310\Lib\site-packages\anyio\_backends\_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "F:\video\rwkv\py310\Lib\site-packages\sse_starlette\sse.py", line 235, in wrap
    await func()
  File "F:\video\rwkv\py310\Lib\site-packages\sse_starlette\sse.py", line 220, in stream_response
    async for data in self.body_iterator:
  File "F:\video\rwkv\backend-python\routes\completion.py", line 315, in eval_rwkv
    response + "\nFinished. RequestsNum: " + str(requests_num),
UnboundLocalError: local variable 'response' referenced before assignment

runner信息
![图片](https://github.com/josStorer/RWKV-Runner/assets/21135502/9b9471e3-11e1-4a52-9c03-52ba78d5672e)
资源用量
![图片](https://github.com/josStorer/RWKV-Runner/assets/21135502/cff33e86-6470-418a-a5f2-464551c1fd66)

**Comment by josStorer** [comment]
什么版本

**Comment by zmengle** [comment]
最新的版本
![图片](https://github.com/josStorer/RWKV-Runner/assets/21135502/7526ef59-5272-4188-a768-6a36cea17519)

**Comment by zmengle** [comment]
偶现，暂不影响使用

**Comment by josStorer** [comment]
出现此错误后，是否还能正常使用

**Comment by zmengle** [comment]
我当时试了下，补全的无法继续输出，关闭模型后再启动就可以了

**Comment by zmengle** [comment]
blocks.31.ffn.value.weight         i8      cpu  16384  4096  (pinned)
ln_out.weight                     f32      cpu   4096
ln_out.bias                       f32      cpu   4096
head.weight                       f32      cpu   4096 50277
F:\video\rwkv\py310\Lib\site-packages\rwkv\model.py:672: UserWarning: operator () profile_node %194 : int = prim::profile_ivalue(%192)
 does not have profile information (Triggered internally at ..\torch\csrc\jit\codegen\cuda\graph_fuser.cpp:109.)
  x, state[i*5+0], state[i*5+1], state[i*5+2], state[i*5+3] = ATT(
INFO:     127.0.0.1:7586 - "POST /switch-model HTTP/1.1" 200 OK
INFO:     127.0.0.1:8375 - "OPTIONS /completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:8375 - "POST /completions HTTP/1.1" 200 OK

小报错

**Comment by josStorer** [comment]
api.log信息给一下

**Comment by josStorer** [comment]
命令行没有其他报错吗
