### ISSUE TITLE
我启动的时候正常 一输入内容开始聊天的时候就报错 错误如下

### ISSUE THREAD

**Issue by xunlingliuxiang** [josStorer/RWKV-Runner#70]
[31mERROR[0m:    Exception in ASGI application
Traceback (most recent call last):
  File "I:\github\chatgpt-RWKV\py310\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "I:\github\chatgpt-RWKV\py310\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "I:\github\chatgpt-RWKV\py310\Lib\site-packages\fastapi\applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "I:\github\chatgpt-RWKV\py310\Lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "I:\github\chatgpt-RWKV\py310\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "I:\github\chatgpt-RWKV\py310\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "I:\github\chatgpt-RWKV\py310\Lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "I:\github\chatgpt-RWKV\py310\Lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "I:\github\chatgpt-RWKV\py310\Lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "I:\github\chatgpt-RWKV\py310\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "I:\github\chatgpt-RWKV\py310\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "I:\github\chatgpt-RWKV\py310\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "I:\github\chatgpt-RWKV\py310\Lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "I:\github\chatgpt-RWKV\py310\Lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "I:\github\chatgpt-RWKV\py310\Lib\site-packages\starlette\routing.py", line 69, in app
    await response(scope, receive, send)
  File "I:\github\chatgpt-RWKV\py310\Lib\site-packages\sse_starlette\sse.py", line 237, in __call__
    async with anyio.create_task_group() as task_group:
  File "I:\github\chatgpt-RWKV\py310\Lib\site-packages\anyio\_backends\_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "I:\github\chatgpt-RWKV\py310\Lib\site-packages\sse_starlette\sse.py", line 240, in wrap
    await func()
  File "I:\github\chatgpt-RWKV\py310\Lib\site-packages\sse_starlette\sse.py", line 225, in stream_response
    async for data in self.body_iterator:
  File "I:\github\chatgpt-RWKV\backend-python\routes\completion.py", line 142, in eval_rwkv
    for response, delta in model.generate(
  File "I:\github\chatgpt-RWKV\backend-python\utils\rwkv.py", line 147, in generate
    token = self.pipeline.sample_logits(
  File "I:\github\chatgpt-RWKV\backend-python\rwkv_pip\utils.py", line 101, in sample_logits
    out = torch.multinomial(probs, num_samples=1)[0]
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

**Comment by josStorer** [comment]
精度问题，小规模world模型，例如0.1B，0.4B，用fp32

**Comment by ocyisheng** [comment]
> 精度问题，小规模world模型，例如0.1B，0.4B，用fp32

使用1.5b word模型int8 fp16会报这个错误，fp32 4G显存有溢出报错。
在使用其他模型时，4G显存使用3B模型并没有问题

**Comment by josStorer** [comment]
小规模world模型必须用fp32，显存不够可以减少载入层数

**Comment by ocyisheng** [comment]
> 小规模world模型必须用fp32，显存不够可以减少载入层数

感觉是模型精度丢失，遇到特殊字符就寄了

**Comment by BlinkDL** [comment]
小world也可以用bf16（略降低精度）

**Comment by josStorer** [comment]
可以考虑直接用3B，3B可以用int8，反而比1.5B省，预设配置里有GPU-4G-3B-World

> > 精度问题，小规模world模型，例如0.1B，0.4B，用fp32
> 
> 使用1.5b word模型int8 fp16会报这个错误，fp32 4G显存有溢出报错。 在使用其他模型时，4G显存使用3B模型并没有问题
