### ISSUE TITLE
访问时Logger会报错，导致结果无法返回

### ISSUE THREAD

**Issue by GuoZhaoJiaRui** [josStorer/RWKV-Runner#71]
--- Logging error ---
Traceback (most recent call last):
  File "logging\__init__.py", line 1103, in emit
UnicodeEncodeError: 'gbk' codec can't encode character '\xa0' in position 571: illegal multibyte sequence
Call stack:
  File "D:\rwkv\backend-python\main.py", line 69, in <module>
    uvicorn.run(
  File "D:\rwkv\py310\Lib\site-packages\uvicorn\main.py", line 578, in run
    server.run()
  File "D:\rwkv\py310\Lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 636, in run_until_complete
  File "asyncio\windows_events.py", line 321, in run_forever
  File "asyncio\base_events.py", line 603, in run_forever
  File "asyncio\base_events.py", line 1909, in _run_once
  File "asyncio\events.py", line 80, in _run
  File "D:\rwkv\py310\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\rwkv\py310\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "D:\rwkv\py310\Lib\site-packages\fastapi\applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "D:\rwkv\py310\Lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\rwkv\py310\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\rwkv\py310\Lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "D:\rwkv\py310\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\rwkv\py310\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "D:\rwkv\py310\Lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "D:\rwkv\py310\Lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\rwkv\py310\Lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "D:\rwkv\py310\Lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "D:\rwkv\py310\Lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "D:\rwkv\backend-python\routes\completion.py", line 193, in eval_rwkv
    for response, delta in model.generate(
  File "D:\rwkv\backend-python\utils\rwkv.py", line 109, in generate
    cache = state_cache.longest_prefix_state(
  File "D:\rwkv\backend-python\routes\state_cache.py", line 125, in longest_prefix_state
    quick_log(request, body, "Hit:\n" + prompt)
  File "D:\rwkv\backend-python\utils\log.py", line 19, in quick_log
    logger.info(
  File "logging\__init__.py", line 1477, in info
  File "logging\__init__.py", line 1624, in _log
  File "logging\__init__.py", line 1634, in handle
  File "logging\__init__.py", line 1696, in callHandlers
  File "logging\__init__.py", line 968, in handle
  File "logging\handlers.py", line 75, in emit
  File "logging\__init__.py", line 1218, in emit
  File "logging\__init__.py", line 1108, in emit
Message: 'Client: \nUrl: \nBody: {"prompt": "\\nThe following is a coherent verbose detailed conversation between a girl named Alice and her friend Bob. Alice is very intelligent, creative and friendly. Alice is unlikely to disagree with Bob, and Alice doesn\'t like to ask Bob questions. Alice likes to tell Bob a lot about herself and her opinions. Alice usually gives Bob kind, helpful and informative advices.\\n\\nBob: 仿照下面\\"\\"\\"中的 Json 格式再生成一个 Json 数据，json 数据要求返回从起点西安到终点新疆的6个沿途著名当地特色目的地，要求6个景区名称列表放在sights 数组中，其他多余字段不要加 ，要求 json 字符串完整\\n\\"\\"\\"\\n{\\n\xa0 \\"sights\\": []\\n}\\n\\"\\"\\"\\n\\nBob: 你好\\n\\nBob: 仿照下面\\"\\"\\"中的 Json 格式再生成一个 Json 数据，json 数据要求返回从起点西安到终点新疆的6个沿途著名当地特色目的地，要求6个景区名称列表放在sights 数组中，其他多余字段不要加，要求 json 字符串完整\\n\\"\\"\\"\\n{\\n\xa0 \\"sights\\": []\\n}\\n\\"\\"\\"\\n\\nBob: 仿照下面\\"\\"\\"中的 Json 格式再生成一个 Json 数据，json 数据要求返回从起点西安到终点新疆的6个沿途著名当地特色 目的地，要求6个景区名称列表放在sights 数组中，其他多余字段不要加，要求 json 字符串完整\\n\\"\\"\\"\\n{\\n\xa0 \\"sights\\": []\\n}\\n\\"\\"\\"\\n\\nBob: 仿照下面\\"\\"\\"中的 Json 格式再生成一个 Json 数据，json 数据要求返回从起点西安到终点 新疆的6个沿途著名当地特色目的地，要求6个景区名称列表放在sights 数组中，其他多余字段不要加，要求 json 字符串完整\\n\\"\\"\\"\\n{\\n\xa0 \\"sights\\": []\\n}\\n\\"\\"\\"\\n\\nBob: 仿照下面\\"\\"\\"中的 Json 格式再生成一个 Json 数据，json 数据要求返回从起点西安到终点新疆的6个沿途著名当地特色目的地，要求6个景区名称列表放在sights 数组中，其他多余字段不要加，要求 json 字符串完整\\n\\"\\"\\"\\n{\\n\xa0 \\"sights\\": []\\n}\\n\\"\\"\\"\\n\\nBob: 你好\\n\\nBob: 仿照下面\\"\\"\\"中的 Json 格式再生成一个 Json 数据，json 数据要求返回从起点西安到终点新疆的6个沿途著名当地特色目的地，要求6个景区名称列表放在sights 数组中，其他多余字段不要加，要求 json 字符串完整\\n\\"\\"\\"\\n{\\n\xa0 \\"sights\\": []\\n}\\n\\"\\"\\"\\n\\nAlice:"}\nData:\nHit:\n\nThe following is a coherent verbose detailed conversation between a girl named Alice and her friend Bob. Alice is very intelligent, creative and friendly. Alice is unlikely to disagree with Bob, and Alice doesn\'t like to ask Bob questions. Alice likes to tell Bob a lot about herself and her opinions. Alice usually gives Bob kind, helpful and informative advices.\n\n\n'
Arguments: ()
Address(host='192.168.1.35', port=33580) Stop Waiting
--- Logging error ---
Traceback (most recent call last):
  File "logging\__init__.py", line 1103, in emit
UnicodeEncodeError: 'gbk' codec can't encode character '\xa0' in position 420: illegal multibyte sequence
Call stack:
  File "D:\rwkv\backend-python\main.py", line 69, in <module>
    uvicorn.run(
  File "D:\rwkv\py310\Lib\site-packages\uvicorn\main.py", line 578, in run
    server.run()
  File "D:\rwkv\py310\Lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 636, in run_until_complete
  File "asyncio\windows_events.py", line 321, in run_forever
  File "asyncio\base_events.py", line 603, in run_forever
  File "asyncio\base_events.py", line 1909, in _run_once
  File "asyncio\events.py", line 80, in _run
  File "D:\rwkv\py310\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\rwkv\py310\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "D:\rwkv\py310\Lib\site-packages\fastapi\applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "D:\rwkv\py310\Lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\rwkv\py310\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\rwkv\py310\Lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "D:\rwkv\py310\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\rwkv\py310\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "D:\rwkv\py310\Lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "D:\rwkv\py310\Lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\rwkv\py310\Lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "D:\rwkv\py310\Lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "D:\rwkv\py310\Lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "D:\rwkv\backend-python\routes\completion.py", line 204, in eval_rwkv
    quick_log(
  File "D:\rwkv\backend-python\utils\log.py", line 19, in quick_log
    logger.info(
  File "logging\__init__.py", line 1477, in info
  File "logging\__init__.py", line 1624, in _log
  File "logging\__init__.py", line 1634, in handle
  File "logging\__init__.py", line 1696, in callHandlers
  File "logging\__init__.py", line 968, in handle
  File "logging\handlers.py", line 75, in emit
  File "logging\__init__.py", line 1218, in emit
  File "logging\__init__.py", line 1108, in emit
Message: 'Client: Address(host=\'192.168.1.35\', port=33580)\nUrl: http://218.61.196.156:10143/chat/completions\nBody: {"max_tokens": null, "temperature": null, "top_p": null, "presence_penalty": null, "frequency_penalty": null, "messages": [{"role": "user", "content": "仿照下面\\"\\"\\"中的 Json 格式再生成一个 Json 数据，json 数据要求返回从起点西安到终点新 疆的6个沿途著名当地特色目的地，要求6个景区名称列表放在sights 数组中，其他多余字段不要加，要求 json 字符串完整\\n\\"\\"\\"\\n{\\n\xa0 \\"sights\\": []\\n}\\n\\"\\"\\""}, {"role": "user", "content": "你好"}, {"role": "user", "content": "仿照 下面\\"\\"\\"中的 Json 格式再生成一个 Json 数据，json 数据要求返回从起点西安到终点新疆的6个沿途著名当地特色目的地，要求6个景区名称列表放在sights 数组中，其他多余字段不要加，要求 json 字符串完整\\n\\"\\"\\"\\n{\\n\xa0 \\"sights\\": []\\n}\\n\\"\\"\\""}, {"role": "user", "content": "仿照下面\\"\\"\\"中的 Json 格式再生成一个 Json 数据，json 数据要求返回从起点西安到终点新疆的6个沿途著名当地特色目的地，要求6个景区名称列表放在sights 数组中，其他多余字段不要加，要求 json 字符串完整\\n\\"\\"\\"\\n{\\n\xa0 \\"sights\\": []\\n}\\n\\"\\"\\""}, {"role": "user", "content": "仿照下面\\"\\"\\"中的 Json 格式 再生成一个 Json 数据，json 数据要求返回从起点西安到终点新疆的6个沿途著名当地特色目的地，要求6个景区名称列表放在sights 数组中，其他多余字段不要加，要求 json 字符串完整\\n\\"\\"\\"\\n{\\n\xa0 \\"sights\\": []\\n}\\n\\"\\"\\""}, {"role": "user", "content": "仿照下面\\"\\"\\"中的 Json 格式再生成一个 Json 数据，json 数据要求返回从起点西安到终点新疆的6个沿途著名当地特色目的地，要求6个景区名称列表放在sights 数组中，其他多余字段不要加，要求 json 字符串完整\\n\\"\\"\\"\\n{\\n\xa0 \\"sights\\": []\\n}\\n\\"\\"\\""}, {"role": "user", "content": "你好"}, {"role": "user", "content": "仿照下面\\"\\"\\"中的 Json 格式再生成一个 Json 数据，json 数据要求返回从起点西安到终点新疆的6个沿途著名当地特色目的地，要求6个景区名称列表放在sights 数组中，其他多余字段不要加，要求 json 字符串完整\\n\\"\\"\\"\\n{\\n\xa0 \\"sights\\": []\\n}\\n\\"\\"\\""}], "model": "gpt-3.5-turbo", "stream": false, "stop": null}\nData:\n 我理解您的需求是，您需要一个包含从起点西安到终点新疆的6个 沿途著名当地特色目的地的JSON数据，并且这些景点名称列表应该按照从起点西安到终点新疆的顺序排列。\n如果您的问题是这样的，那么您可以使用以下的Python代码来实现这个功能：\n```python\nimport json\ndef generate_sights_data(start_place, end_place):\n    sight_data = []\n    sight_data.append({\n        "name": start_place,\n        "location": start_place\n    })\n    sight_data.append({\n        "name": end_place,\n        "location": end_place\n    })\n    return json.dumps(sight_data)\n```\n在这个代码中，我们定义了一个名为`generate_sights_data`的函数，该函数接受两个参数`start_place`和`end_place`，分别表示起点和终点的地点名称。\n在函数的主体中，我们使用了Python的`json`模块来生成一个JSON格式的数据，并将其保存在`sight_data`变量中。\n最后，我们使用`json.dumps`函数将`sight_data`变量的内容转换为JSON格式的字符串，并将其作为`sight_data`的`sights`的`data`的`data`的`data`的`data`的`data`的`data`的`data`的`data`的`data`的`data`的`data`的`data\nStop Waiting. RequestsNum: 0\n'

**Comment by josStorer** [comment]
是1.2.2版本吗，昨天的更新已经catch住了
